GET http://localhost:8883/api.php?auth=CHANGE_THIS_TO_A_RANDOM_STRING
Accept: application/json

###

POST http://localhost:8883/api.php?auth=CHANGE_THIS_TO_A_RANDOM_STRING&action=set
Content-Type: application/json

{"key": "test", "value": [1,2,{"message": "hello"}]}


###

POST http://localhost:8883/api.php?auth=CHANGE_THIS_TO_A_RANDOM_STRING&action=set
Content-Type: application/json

{"key": "list", "value": []}

###

POST http://localhost:8883/api.php?auth=CHANGE_THIS_TO_A_RANDOM_STRING&action=unset
Content-Type: application/json

{"key": "list"}

###


POST http://localhost:8883/api.php?auth=CHANGE_THIS_TO_A_RANDOM_STRING&action=add
Content-Type: application/json

{"key": "list", "value": {"message": "yay7"}}

###


POST http://localhost:8883/api.php?auth=CHANGE_THIS_TO_A_RANDOM_STRING&action=update
Content-Type: application/json

{"key": "list", "id":9, "value": {"message": "yay9"}}

###


POST http://localhost:8883/api.php?auth=CHANGE_THIS_TO_A_RANDOM_STRING&action=delete
Content-Type: application/json

{"key": "list", "id":32}

###
